const READ_FILES = 'READ_FILES';
const CHANGE_LETTER_COLOR = 'CHANGE_LETTER_COLOR';
const DRAW_LETTER = 'DRAW_LETTER';
const TRAIN_AI = 'TRAIN_AI';
const FIND_CORRECT_LETTER = 'FIND_CORRECT_LETTER';
const SUBMIT_FORM = 'SUBMIT_FORM';

export {READ_FILES, CHANGE_LETTER_COLOR, DRAW_LETTER, TRAIN_AI, FIND_CORRECT_LETTER, SUBMIT_FORM}